version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: carrier_rate_raw
        meta:
          dagster:
            asset_key: ["carrier_rate_raw"]
      - name: shipment_events_raw
        meta:
          dagster:
            asset_key: ["shipment_events_raw"]
      - name: salesforce_accounts
        meta:
          dagster:
            asset_key: ["salesforce_accounts"]
      - name: zendesk_tickets
        meta:
          dagster:
            asset_key: ["zendesk_tickets"]
      - name: netsuite_gl_entries
        meta:
          dagster:
            asset_key: ["netsuite_gl_entries"]
